[package]
name = "ocean"
version = "0.1.0"
authors = ["Benjamin Große <benjamin@midokura.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
#bevy = "0.3.0" # make sure this is the latest version
#bevy_prototype_input_map = "0.1"
bevy = { git = "https://github.com/bevyengine/bevy", rev = "4fecb899" }
#bevy_prototype_input_map = { git = "https://github.com/PradeepKumarRajamanickam/bevy_input_map/" }
