[package]
name = "ocean"
version = "0.1.0"
authors = ["Benjamin Große <benjamin@midokura.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev.package."*"]
opt-level = 3

# [features]
# default = [
  # "bevy/bevy_gltf",
  # "bevy/bevy_winit",
  # "bevy/render",
  # "bevy/png",
# ]
#
# native = [
  # "bevy/bevy_wgpu",
# ]
#
# web = [
  # "bevy_webgl2"
# ]

[dependencies]
bevy = "0.5.0"
rand = "0.7"
bevy_prototype_debug_lines = "0.2.0"
# bevy = {version="0.4.0", default-features=false}
# bevy_webgl2 = {version="0.4.0", optional=true}

# winit = {version = "0.24.0"}
# getrandom = {version="0.1", features=["wasm-bindgen"]}
